"""
Production BLIP image-captioning wrapper.

Features:
- Loads BLIP once per process
- CPU/GPU support
- Controlled text generation
- Repetition prevention
- Better caption length control
- Safe fallback on generation errors
"""

import threading

import torch
from PIL import Image
from transformers import BlipProcessor, BlipForConditionalGeneration

from app.config import get_settings


settings = get_settings()

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

_lock = threading.Lock()

_processor: BlipProcessor | None = None
_model: BlipForConditionalGeneration | None = None


def _load():
    global _processor, _model

    if _model is None:
        with _lock:
            if _model is None:
                print(f"Loading BLIP model: {settings.BLIP_MODEL_NAME}")

                _processor = BlipProcessor.from_pretrained(
                    settings.BLIP_MODEL_NAME
                )

                _model = BlipForConditionalGeneration.from_pretrained(
                    settings.BLIP_MODEL_NAME
                ).to(DEVICE)

                _model.eval()

                print(
                    f"✅ BLIP model loaded successfully on {DEVICE}"
                )

    return _processor, _model


def _clean_caption(text: str) -> str:
    """
    Remove obvious repetitive phrases generated by BLIP.
    """

    text = " ".join(text.strip().split())

    if not text:
        return ""

    words = text.split()

    # Prevent excessive consecutive word repetition.
    cleaned_words = []

    for word in words:
        if len(cleaned_words) >= 2:
            if (
                cleaned_words[-1].lower() == word.lower()
                and cleaned_words[-2].lower() == word.lower()
            ):
                continue

        cleaned_words.append(word)

    text = " ".join(cleaned_words)

    # Additional protection against repeated 2-word phrases.
    words = text.split()

    if len(words) >= 6:
        final_words = []

        i = 0

        while i < len(words):
            if (
                i + 3 < len(words)
                and words[i].lower() == words[i + 2].lower()
                and words[i + 1].lower() == words[i + 3].lower()
            ):
                final_words.extend(words[i:i + 2])
                i += 4
            else:
                final_words.append(words[i])
                i += 1

        text = " ".join(final_words)

    return text.strip()


@torch.inference_mode()
def generate_caption(image_pil: Image.Image) -> str:
    """
    Generate a concise image caption using BLIP.
    """

    processor, model = _load()

    try:
        if image_pil is None:
            return "Caption unavailable."

        image = image_pil.convert("RGB")

        inputs = processor(
            images=image,
            return_tensors="pt",
        ).to(DEVICE)

        output_ids = model.generate(
            **inputs,

            # Caption length
            max_new_tokens=30,
            min_new_tokens=5,

            # Better generation quality
            num_beams=5,

            # Prevent repetitive captions
            no_repeat_ngram_size=3,
            repetition_penalty=1.2,

            # Stop when caption is complete
            early_stopping=True,
        )

        caption = processor.decode(
            output_ids[0],
            skip_special_tokens=True,
        )

        caption = _clean_caption(caption)

        if not caption:
            return "Caption unavailable."

        return caption

    except Exception as exc:
        print(f"⚠️ BLIP caption generation failed: {exc}")
        return "Caption unavailable."